language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
before_install:
- chmod +x gradlew
branches:
  only:
  - master
script:
- "./gradlew build assembleRelease"
notifications:
  email: true
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: yguO3YosObFbMH12FbwLS33FbYde5hDJD4Bl6G+rlXHNfnwRblGkAwUzDV3v4e7KEpaT08AsNmSfcM/WMqNhigP4NLXHc0ERSBr/AX8l2NiLB+Cn9NyvXbJQmJIa6qqcpFU+0kKPjytN7cBZtxcI/h9QgLjNivP+lAhp1+d609ZaIUhZS57xfCJ85jlZa2FMR9GzQ+DHu0Oqc4Y10yTHTQguGXYYrZGNeyd9+xsTpNyYQPBfLFSuKMcQ772xFzqGkPBCiitFSqXqDcP4EY3ZbH9PJkEaUcpyE3pEEvF7vSaPxMvvNYgCe9IRuKNPb2ZQDiAsGqPpWDIxEKW7R/etJESHNPaUEMKJSRZWgATIaigdAtuV8pO32J/UvrZsVxzCqbFW8Qa/4VsJLUu0JHGLqqttKyhZoRcUSs3wlVu1TkJjcK/cO+wpIlJmS7btM5xeapBHstlZnULe5P8GroTKDL581EJ7J0C0zB4EZ/0WQbM2x00xrM4vTO6KkutY4Ohku3l96i2YXdbdUfiCzuE5CwZimOQdI75Fx3PSSzlMH7DjLA1STszkXq6jQ7TABdCoDb3mdaGF2qo2c4Ui2L8c4IDUv1MlFle8Nz4Dh6rMr2KwA3jG19kBzKkCQYvnrAPNzYOIbO+SifqzwpJrIs3Y0wbRk/TWncBVOLDq8E5T2bU=
  file: "/app/build/outputs/test.apk"
  file: app/build/outputs/apk/HSRmarket_V0_${TRAVIS_BUILD_NUMBER}.apk
  file_glob: "true"
  skip_cleanup: true
  on:
  branch: master
  repo: hsrmarket/app-android
  tags: true	