language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - sys-img-armeabi-v7a-android-25

before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android_sdk_license"

script:
- ./gradlew build connectedCheck
