language: android
sudo: required
jdk: oraclejdk8
android:


before_install:
    - rm -rf $ANDROID_HOME/*
    - wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip -O $ANDROID_HOME/sdk.zip
    - unzip $ANDROID_HOME/sdk.zip
    - mv $ANDROID_HOME/tools/* $ANDROID_HOME/

    - echo y | $ANDROID_HOME/bin/sdkmanager "build-tools;25.0.2"
    - echo y | $ANDROID_HOME/bin/sdkmanager "platforms;android-25"
    - echo y | $ANDROID_HOME/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
    - echo y | $ANDROID_HOME/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"


    - chmod +x gradlew
    - ./gradlew dependencies || true

script:
    - ./gradlew clean build connectedCheck --stacktrace

notifications:
  email: false
